#
# Copyright 2011 Nathan Fiedler. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
#
# $Id$
#

include $(GOROOT)/src/Make.inc

TARG=sortingo
GOFILES=\
	combsort.go\
	gnomesort.go\
	insertionsort.go\

include $(GOROOT)/src/Make.pkg
