#
# Copyright 2011 Nathan Fiedler. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
#

include $(GOROOT)/src/Make.inc

TARG=sortingo
GOFILES=\
	binaryinsertionsort.go\
	burstsort.go\
	dualpivotquicksort.go\
	combsort.go\
	gnomesort.go\
	heapsort.go\
	hybridcombsort.go\
	insertionsort.go\
	mergesort.go\
	multikeyquicksort.go\
	selectionsort.go\
	shellsort.go\

include $(GOROOT)/src/Make.pkg
