#
# Copyright 2011 Nathan Fiedler. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
#
# $Id: $
#
# This makefile is used to run the unit tests.
#

include $(GOROOT)/src/Make.inc

SRC=.

TARG=sortingo
GOFILES=\
	$(SRC)/combsort.go\
	$(SRC)/insertionsort.go\

include $(GOROOT)/src/Make.pkg
